export const THEMES = [
  { slug: 'numbers',  title: 'Numbers',  chinese: '数字', pinyin: 'shu4 zi4', desc: 'Count, measure, and ask how many' },
  { slug: 'colors',   title: 'Colors',   chinese: '颜色', pinyin: 'yan2 se4', desc: 'Describe shades and appearances' },
  { slug: 'family',   title: 'Family',   chinese: '家庭', pinyin: 'jia1 ting2', desc: 'Relatives and household members' },
  { slug: 'time',     title: 'Time',     chinese: '时间', pinyin: 'shi2 jian1', desc: 'Days, dates, seasons, and clocks' },
  { slug: 'food',     title: 'Food',     chinese: '食物', pinyin: 'shi2 wu4', desc: 'Ingredients, dishes, drinks, and flavours' },
  { slug: 'weather',  title: 'Weather',  chinese: '天气', pinyin: 'tian1 qi4', desc: 'Conditions, temperature, and seasons' },
  { slug: 'body',     title: 'Body',     chinese: '身体', pinyin: 'shen1 ti3', desc: 'Body parts and common health vocabulary' },
  { slug: 'animals',  title: 'Animals',  chinese: '动物', pinyin: 'dong4 wu4', desc: 'Pets, wildlife, and creatures of all kinds' },
];

export const WORD_DATA = {
  numbers: {
    sections: [
      {
        heading: 'Basic numbers (0–10)',
        words: [
          { s: '零', py: 'ling2', en: 'zero' },
          { s: '一', py: 'yi1', en: 'one' },
          { s: '二', py: 'er4', en: 'two' },
          { s: '三', py: 'san1', en: 'three' },
          { s: '四', py: 'si4', en: 'four' },
          { s: '五', py: 'wu3', en: 'five' },
          { s: '六', py: 'liu4', en: 'six' },
          { s: '七', py: 'qi1', en: 'seven' },
          { s: '八', py: 'ba1', en: 'eight' },
          { s: '九', py: 'jiu3', en: 'nine' },
          { s: '十', py: 'shi2', en: 'ten' },
        ],
      },
      {
        heading: 'Larger numbers',
        words: [
          { s: '十一', py: 'shi2 yi1', en: 'eleven' },
          { s: '十二', py: 'shi2 er4', en: 'twelve' },
          { s: '二十', py: 'er4 shi2', en: 'twenty' },
          { s: '一百', py: 'yi1 bai3', en: 'one hundred' },
          { s: '一千', py: 'yi1 qian1', en: 'one thousand' },
          { s: '一万', py: 'yi1 wan4', en: 'ten thousand',
            note: 'Chinese groups numbers by 万 (ten-thousands), not thousands — so 100,000 is 十万 (ten 万), and 1,000,000 is 一百万 (one hundred 万)' },
          { s: '十万', py: 'shi2 wan4', en: 'one hundred thousand' },
          { s: '一百万', py: 'yi1 bai3 wan4', en: 'one million' },
          { s: '一千万', py: 'yi1 qian1 wan4', en: 'ten million' },
          { s: '一亿', py: 'yi1 yi4', en: 'one hundred million' },
        ],
      },
      {
        heading: 'Useful number words',
        words: [
          { s: '两', py: 'liang3', en: 'two (before measure words)', note: 'Use 两 instead of 二 before measure words: 两个 = two [things], 两本书 = two books' },
          { s: '双', py: 'shuang1', en: 'pair; double; even number' },
          { s: '半', py: 'ban4', en: 'half' },
          { s: '第', py: 'di4', en: 'ordinal prefix', note: '第一 = first, 第二 = second — placed before any number to make it ordinal' },
          { s: '数字', py: 'shu4 zi4', en: 'number; digit; numeral' },
          { s: '号码', py: 'hao4 ma3', en: 'number (phone, ID, etc.)' },
          { s: '多少', py: 'duo1 shao3', en: 'how many; how much' },
          { s: '几', py: 'ji3', en: 'how many (small number); several', note: '几 implies a smaller, countable quantity — use it when expecting single digits' },
        ],
      },
    ],
  },

  colors: {
    sections: [
      {
        heading: 'Colors',
        words: [
          { s: '颜色', py: 'yan2 se4', en: 'color; colour' },
          { s: '红色', py: 'hong2 se4', en: 'red' },
          { s: '橙色', py: 'cheng2 se4', en: 'orange' },
          { s: '黄色', py: 'huang2 se4', en: 'yellow' },
          { s: '绿色', py: 'lu:4 se4', en: 'green' },
          { s: '蓝色', py: 'lan2 se4', en: 'blue' },
          { s: '紫色', py: 'zi3 se4', en: 'purple' },
          { s: '粉色', py: 'fen3 se4', en: 'pink' },
          { s: '白色', py: 'bai2 se4', en: 'white' },
          { s: '黑色', py: 'hei1 se4', en: 'black' },
          { s: '灰色', py: 'hui1 se4', en: 'grey' },
          { s: '棕色', py: 'zong1 se4', en: 'brown' },
          { s: '金色', py: 'jin1 se4', en: 'gold; golden' },
          { s: '银色', py: 'yin2 se4', en: 'silver' },
          { s: '透明', py: 'tou4 ming2', en: 'transparent; clear' },
        ],
      },
      {
        heading: 'Modifiers',
        words: [
          { s: '浅', py: 'qian3', en: 'light (pale shade)', note: '浅蓝色 = light blue; 浅红色 = light red' },
          { s: '深', py: 'shen1', en: 'dark (deep shade)', note: '深蓝色 = dark blue; 深绿色 = dark green' },
        ],
      },
    ],
  },

  family: {
    sections: [
      {
        heading: 'Immediate family',
        words: [
          { s: '家庭', py: 'jia1 ting2', en: 'family; household' },
          { s: '家人', py: 'jia1 ren2', en: 'family members' },
          { s: '爸妈', py: 'ba4 ma1', en: 'mom and dad (together)', note: 'The most natural colloquial way to refer to both parents' },
          { s: '爸爸', py: 'ba4 ba5', en: 'dad; father', variant: { s: '父亲', py: 'fu4 qin1', label: 'formal / written' } },
          { s: '妈妈', py: 'ma1 ma5', en: 'mum; mother', variant: { s: '母亲', py: 'mu3 qin1', label: 'formal / written' } },
          { s: '父母', py: 'fu4 mu3', en: 'parents (formal)' },
          { s: '哥哥', py: 'ge1 ge5', en: 'older brother' },
          { s: '弟弟', py: 'di4 di5', en: 'younger brother' },
          { s: '姐姐', py: 'jie3 jie5', en: 'older sister' },
          { s: '妹妹', py: 'mei4 mei5', en: 'younger sister' },
          { s: '兄弟姐妹', py: 'xiong1 di4 jie3 mei4', en: 'siblings' },
          { s: '儿子', py: 'er2 zi5', en: 'son' },
          { s: '女儿', py: 'nu:3 er2', en: 'daughter' },
          { s: '孩子', py: 'hai2 zi5', en: 'child; children', variant: { s: '小孩', py: 'xiao3 hai2', label: 'slightly more colloquial' } },
        ],
      },
      {
        heading: 'Grandparents',
        words: [
          { s: '爷爷', py: 'ye2 ye5', en: 'paternal grandfather' },
          { s: '奶奶', py: 'nai3 nai5', en: 'paternal grandmother' },
          { s: '外公', py: 'wai4 gong1', en: 'maternal grandfather',
            variant: { s: '姥爷', py: 'lao3 ye5', label: 'northern China' },
            note: '外公 is used in southern China and Taiwan; 姥爷 is common in the north' },
          { s: '外婆', py: 'wai4 po2', en: 'maternal grandmother',
            variant: { s: '姥姥', py: 'lao3 lao5', label: 'northern China' } },
          { s: '孙子', py: 'sun1 zi3', en: 'grandson (son\'s son)' },
          { s: '孙女', py: 'sun1 nu:3', en: 'granddaughter (son\'s daughter)' },
        ],
      },
      {
        heading: 'Spouse & in-laws',
        words: [
          { s: '丈夫', py: 'zhang4 fu5', en: 'husband',
            variant: { s: '老公', py: 'lao3 gong1', label: 'colloquial, very common' } },
          { s: '妻子', py: 'qi1 zi5', en: 'wife',
            variant: { s: '老婆', py: 'lao3 po2', label: 'colloquial' },
            note: '太太 (tài tai) is also common, especially in Taiwan' },
          { s: '公公', py: 'gong1 gong5', en: 'husband\'s father' },
          { s: '婆婆', py: 'po2 po5', en: 'husband\'s mother' },
          { s: '岳父', py: 'yue4 fu4', en: 'wife\'s father' },
          { s: '岳母', py: 'yue4 mu3', en: 'wife\'s mother' },
          { s: '继父', py: 'ji4 fu4', en: 'stepfather' },
          { s: '继母', py: 'ji4 mu3', en: 'stepmother' },
        ],
      },
      {
        heading: 'Extended family & cousins',
        words: [
          { s: '表哥', py: 'biao3 ge1', en: 'older male cousin (maternal side)' },
          { s: '表弟', py: 'biao3 di4', en: 'younger male cousin (maternal side)' },
          { s: '表姐', py: 'biao3 jie3', en: 'older female cousin (maternal side)' },
          { s: '表妹', py: 'biao3 mei4', en: 'younger female cousin (maternal side)' },
          { s: '堂哥', py: 'tang2 ge1', en: 'older male cousin (paternal side)' },
          { s: '堂弟', py: 'tang2 di4', en: 'younger male cousin (paternal side)' },
          { s: '堂姐', py: 'tang2 jie3', en: 'older female cousin (paternal side)' },
          { s: '堂妹', py: 'tang2 mei4', en: 'younger female cousin (paternal side)' },
          { s: '叔叔', py: 'shu1 shu5', en: 'uncle (father\'s younger brother)' },
          { s: '伯伯', py: 'bo2 bo5', en: 'uncle (father\'s older brother)' },
          { s: '阿姨', py: 'a1 yi2', en: 'aunt (mother\'s sister)', note: 'Also used as a polite form of address for older women you\'re not related to' },
          { s: '姑姑', py: 'gu1 gu5', en: 'aunt (father\'s sister)' },
          { s: '舅舅', py: 'jiu4 jiu5', en: 'uncle (mother\'s brother)' },
          { s: '亲戚', py: 'qin1 qi5', en: 'relative; family member (extended)' },
        ],
      },
    ],
  },

  time: {
    sections: [
      {
        heading: 'Days of the week',
        words: [
          { s: '星期一', py: 'xing1 qi1 yi1', en: 'Monday', variant: { s: '周一', py: 'zhou1 yi1', label: '周 form, equally common' } },
          { s: '星期二', py: 'xing1 qi1 er4', en: 'Tuesday', variant: { s: '周二', py: 'zhou1 er4', label: '周 form' } },
          { s: '星期三', py: 'xing1 qi1 san1', en: 'Wednesday', variant: { s: '周三', py: 'zhou1 san1', label: '周 form' } },
          { s: '星期四', py: 'xing1 qi1 si4', en: 'Thursday', variant: { s: '周四', py: 'zhou1 si4', label: '周 form' } },
          { s: '星期五', py: 'xing1 qi1 wu3', en: 'Friday', variant: { s: '周五', py: 'zhou1 wu3', label: '周 form' } },
          { s: '星期六', py: 'xing1 qi1 liu4', en: 'Saturday', variant: { s: '周六', py: 'zhou1 liu4', label: '周 form' } },
          { s: '星期天', py: 'xing1 qi1 tian1', en: 'Sunday', variant: { s: '周日', py: 'zhou1 ri4', label: '周 form; also 星期日' } },
          { s: '周末', py: 'zhou1 mo4', en: 'weekend' },
        ],
      },
      {
        heading: 'Months',
        words: [
          { s: '一月', py: 'yi1 yue4', en: 'January' },
          { s: '二月', py: 'er4 yue4', en: 'February' },
          { s: '三月', py: 'san1 yue4', en: 'March' },
          { s: '四月', py: 'si4 yue4', en: 'April' },
          { s: '五月', py: 'wu3 yue4', en: 'May' },
          { s: '六月', py: 'liu4 yue4', en: 'June' },
          { s: '七月', py: 'qi1 yue4', en: 'July' },
          { s: '八月', py: 'ba1 yue4', en: 'August' },
          { s: '九月', py: 'jiu3 yue4', en: 'September' },
          { s: '十月', py: 'shi2 yue4', en: 'October' },
          { s: '十一月', py: 'shi2 yi1 yue4', en: 'November' },
          { s: '十二月', py: 'shi2 er4 yue4', en: 'December' },
        ],
      },
      {
        heading: 'Relative time',
        words: [
          { s: '现在', py: 'xian4 zai4', en: 'now; at present' },
          { s: '今天', py: 'jin1 tian1', en: 'today' },
          { s: '昨天', py: 'zuo2 tian1', en: 'yesterday' },
          { s: '明天', py: 'ming2 tian1', en: 'tomorrow' },
          { s: '后天', py: 'hou4 tian1', en: 'the day after tomorrow' },
          { s: '前天', py: 'qian2 tian1', en: 'the day before yesterday' },
          { s: '今年', py: 'jin1 nian2', en: 'this year' },
          { s: '去年', py: 'qu4 nian2', en: 'last year' },
          { s: '明年', py: 'ming2 nian2', en: 'next year' },
          { s: '这周', py: 'zhe4 zhou1', en: 'this week', variant: { s: '这个星期', py: 'zhe4 ge5 xing1 qi1', label: 'full form' } },
          { s: '上周', py: 'shang4 zhou1', en: 'last week', variant: { s: '上个星期', py: 'shang4 ge5 xing1 qi1', label: 'full form' } },
          { s: '下周', py: 'xia4 zhou1', en: 'next week', variant: { s: '下个星期', py: 'xia4 ge5 xing1 qi1', label: 'full form' } },
        ],
      },
      {
        heading: 'Times of day',
        words: [
          { s: '凌晨', py: 'ling2 chen2', en: 'the hours after midnight, before dawn' },
          { s: '早上', py: 'zao3 shang5', en: 'morning (early)' },
          { s: '上午', py: 'shang4 wu3', en: 'morning; a.m.' },
          { s: '中午', py: 'zhong1 wu3', en: 'noon; midday' },
          { s: '下午', py: 'xia4 wu3', en: 'afternoon; p.m.' },
          { s: '傍晚', py: 'bang4 wan3', en: 'dusk; early evening' },
          { s: '晚上', py: 'wan3 shang5', en: 'evening; night' },
          { s: '夜里', py: 'ye4 li5', en: 'at night; in the night' },
        ],
      },
      {
        heading: 'Time units & expressions',
        words: [
          { s: '小时', py: 'xiao3 shi2', en: 'hour' },
          { s: '分钟', py: 'fen1 zhong1', en: 'minute' },
          { s: '秒', py: 'miao3', en: 'second' },
          { s: '时间', py: 'shi2 jian1', en: 'time' },
          { s: '时候', py: 'shi2 hou5', en: 'moment; (the) time when' },
          { s: '以前', py: 'yi3 qian2', en: 'before; in the past; previously' },
          { s: '以后', py: 'yi3 hou4', en: 'after; in the future; afterwards' },
          { s: '季节', py: 'ji4 jie2', en: 'season' },
          { s: '春天', py: 'chun1 tian1', en: 'spring' },
          { s: '夏天', py: 'xia4 tian1', en: 'summer' },
          { s: '秋天', py: 'qiu1 tian1', en: 'autumn; fall' },
          { s: '冬天', py: 'dong1 tian1', en: 'winter' },
        ],
      },
    ],
  },

  food: {
    sections: [
      {
        heading: 'Staples & grains',
        words: [
          { s: '米饭', py: 'mi3 fan4', en: 'cooked rice' },
          { s: '面', py: 'mian4', en: 'noodles; pasta; flour-based dishes' },
          { s: '面条', py: 'mian4 tiao2', en: 'noodles (the specific term)' },
          { s: '包子', py: 'bao1 zi5', en: 'steamed bun with filling' },
          { s: '馒头', py: 'man2 tou5', en: 'plain steamed bun (no filling)' },
          { s: '饺子', py: 'jiao3 zi5', en: 'dumplings' },
          { s: '粥', py: 'zhou1', en: 'congee; rice porridge' },
          { s: '面包', py: 'mian4 bao1', en: 'bread' },
        ],
      },
      {
        heading: 'Meat & protein',
        words: [
          { s: '肉', py: 'rou4', en: 'meat' },
          { s: '猪肉', py: 'zhu1 rou4', en: 'pork' },
          { s: '牛肉', py: 'niu2 rou4', en: 'beef' },
          { s: '鸡肉', py: 'ji1 rou4', en: 'chicken' },
          { s: '羊肉', py: 'yang2 rou4', en: 'lamb; mutton' },
          { s: '鱼', py: 'yu2', en: 'fish' },
          { s: '虾', py: 'xia1', en: 'shrimp; prawns' },
          { s: '鸡蛋', py: 'ji1 dan4', en: 'egg' },
          { s: '豆腐', py: 'dou4 fu5', en: 'tofu' },
        ],
      },
      {
        heading: 'Vegetables',
        words: [
          { s: '蔬菜', py: 'shu1 cai4', en: 'vegetables' },
          { s: '西红柿', py: 'xi1 hong2 shi4', en: 'tomato',
            variant: { s: '番茄', py: 'fan1 qie2', label: 'south China & Taiwan' } },
          { s: '土豆', py: 'tu3 dou4', en: 'potato',
            variant: { s: '马铃薯', py: 'ma3 ling2 shu3', label: 'formal, also Taiwan' },
            note: '土豆 is everyday usage; 马铃薯 is the formal/literary term' },
          { s: '黄瓜', py: 'huang2 gua1', en: 'cucumber' },
          { s: '白菜', py: 'bai2 cai4', en: 'Chinese cabbage; napa cabbage' },
          { s: '菠菜', py: 'bo1 cai4', en: 'spinach' },
          { s: '茄子', py: 'qie2 zi5', en: 'eggplant; aubergine' },
          { s: '洋葱', py: 'yang2 cong1', en: 'onion' },
          { s: '大蒜', py: 'da4 suan4', en: 'garlic' },
          { s: '生姜', py: 'sheng1 jiang1', en: 'ginger' },
          { s: '辣椒', py: 'la4 jiao1', en: 'chili pepper' },
          { s: '青椒', py: 'qing1 jiao1', en: 'green bell pepper; capsicum',
            variant: { s: '甜椒', py: 'tian2 jiao1', label: 'sweet / coloured peppers' },
            note: '青椒 usually means green pepper; 甜椒 for red, yellow, or orange varieties' },
          { s: '蘑菇', py: 'mo2 gu5', en: 'mushroom' },
          { s: '玉米', py: 'yu4 mi3', en: 'corn; maize' },
          { s: '胡萝卜', py: 'hu2 luo2 bo5', en: 'carrot' },
        ],
      },
      {
        heading: 'Fruit',
        words: [
          { s: '水果', py: 'shui3 guo3', en: 'fruit' },
          { s: '苹果', py: 'ping2 guo3', en: 'apple' },
          { s: '香蕉', py: 'xiang1 jiao1', en: 'banana' },
          { s: '西瓜', py: 'xi1 gua1', en: 'watermelon' },
          { s: '橙子', py: 'cheng2 zi5', en: 'orange' },
          { s: '葡萄', py: 'pu2 tao5', en: 'grapes' },
          { s: '草莓', py: 'cao3 mei2', en: 'strawberry' },
          { s: '树莓', py: 'shu4 mei2', en: 'raspberry' },
          { s: '芒果', py: 'mang2 guo3', en: 'mango' },
          { s: '桃子', py: 'tao2 zi5', en: 'peach' },
          { s: '梨', py: 'li2', en: 'pear' },
          { s: '菠萝', py: 'bo1 luo2', en: 'pineapple',
            variant: { s: '凤梨', py: 'feng4 li2', label: 'Taiwan' } },
          { s: '牛油果', py: 'niu2 you2 guo3', en: 'avocado',
            variant: { s: '酪梨', py: 'lao4 li2', label: 'Taiwan' } },
          { s: '榴莲', py: 'liu2 lian2', en: 'durian' },
          { s: '荔枝', py: 'li4 zhi1', en: 'lychee' },
        ],
      },
      {
        heading: 'Drinks',
        words: [
          { s: '水', py: 'shui3', en: 'water' },
          { s: '茶', py: 'cha2', en: 'tea' },
          { s: '咖啡', py: 'ka1 fei1', en: 'coffee' },
          { s: '果汁', py: 'guo3 zhi1', en: 'juice' },
          { s: '牛奶', py: 'niu2 nai3', en: 'milk' },
          { s: '可乐', py: 'ke3 le4', en: 'cola (Coke / Pepsi)' },
          { s: '汽水', py: 'qi4 shui3', en: 'soda; fizzy drink' },
          { s: '气泡水', py: 'qi4 pao4 shui3', en: 'sparkling water' },
          { s: '奶茶', py: 'nai3 cha2', en: 'milk tea' },
          { s: '啤酒', py: 'pi2 jiu3', en: 'beer' },
          { s: '白酒', py: 'bai2 jiu3', en: 'Chinese baijiu (clear grain spirit)' },
          { s: '红酒', py: 'hong2 jiu3', en: 'red wine' },
          { s: '白葡萄酒', py: 'bai2 pu2 tao5 jiu3', en: 'white wine' },
          { s: '威士忌', py: 'wei1 shi4 ji4', en: 'whisky' },
          { s: '伏特加', py: 'fu2 te4 jia1', en: 'vodka' },
          { s: '鸡尾酒', py: 'ji1 wei3 jiu3', en: 'cocktail' },
        ],
      },
      {
        heading: 'Taste & cooking',
        words: [
          { s: '辣', py: 'la4', en: 'spicy; hot (chili)' },
          { s: '甜', py: 'tian2', en: 'sweet' },
          { s: '咸', py: 'xian2', en: 'salty' },
          { s: '酸', py: 'suan1', en: 'sour' },
          { s: '苦', py: 'ku3', en: 'bitter' },
          { s: '烫', py: 'tang4', en: 'scalding hot (food or drink temperature)' },
          { s: '凉', py: 'liang2', en: 'cool; cold (food temperature)',
            note: 'Not as cold as 冰 (bīng) — 凉 is room temperature or mildly chilled' },
          { s: '油腻', py: 'you2 ni4', en: 'greasy; oily' },
          { s: '淡', py: 'dan4', en: 'bland; mild (taste)' },
          { s: '清淡', py: 'qing1 dan4', en: 'light; not rich',
            note: 'Describes a cooking style as well as a taste — opposite of 油腻' },
          { s: '好吃', py: 'hao3 chi1', en: 'delicious; tasty' },
          { s: '不好吃', py: 'bu4 hao3 chi1', en: 'not tasty; unpalatable',
            variant: { s: '难吃', py: 'nan2 chi1', label: 'stronger: awful, disgusting' },
            note: '不好吃 is neutral; 难吃 is stronger and more emphatic' },
        ],
      },
    ],
  },

  weather: {
    sections: [
      {
        heading: 'Conditions',
        words: [
          { s: '晴天', py: 'qing2 tian1', en: 'sunny; clear sky' },
          { s: '多云', py: 'duo1 yun2', en: 'cloudy' },
          { s: '阴天', py: 'yin1 tian1', en: 'overcast' },
          { s: '下雨', py: 'xia4 yu3', en: 'to rain' },
          { s: '下雪', py: 'xia4 xue3', en: 'to snow' },
          { s: '刮风', py: 'gua1 feng1', en: 'to be windy' },
          { s: '打雷', py: 'da3 lei2', en: 'thunder' },
          { s: '闪电', py: 'shan3 dian4', en: 'lightning' },
          { s: '雾', py: 'wu4', en: 'fog; mist (natural)' },
          { s: '雾霾', py: 'wu4 mai2', en: 'smog; haze',
            note: '雾 is natural fog; 霾 is pollution haze; 雾霾 is the combination — very common in northern Chinese cities' },
          { s: '台风', py: 'tai2 feng1', en: 'typhoon' },
        ],
      },
      {
        heading: 'Temperature & conditions',
        words: [
          { s: '热', py: 're4', en: 'hot' },
          { s: '冷', py: 'leng3', en: 'cold' },
          { s: '暖和', py: 'nuan3 huo5', en: 'warm' },
          { s: '凉快', py: 'liang2 kuai5', en: 'cool; pleasantly cool' },
          { s: '潮湿', py: 'chao2 shi1', en: 'humid; damp' },
          { s: '干燥', py: 'gan1 zao4', en: 'dry' },
          { s: '温度', py: 'wen1 du4', en: 'temperature' },
          { s: '度', py: 'du4', en: 'degree (°C)' },
          { s: '空气质量', py: 'kong1 qi4 zhi4 liang4', en: 'air quality' },
        ],
      },
    ],
  },

  body: {
    sections: [
      {
        heading: 'Head & face',
        words: [
          { s: '头', py: 'tou2', en: 'head' },
          { s: '脸', py: 'lian3', en: 'face' },
          { s: '头发', py: 'tou2 fa5', en: 'hair (on the head)' },
          { s: '胡子', py: 'hu2 zi5', en: 'beard; moustache' },
          { s: '眼睛', py: 'yan3 jing5', en: 'eyes' },
          { s: '耳朵', py: 'er3 duo5', en: 'ears' },
          { s: '鼻子', py: 'bi2 zi5', en: 'nose' },
          { s: '嘴', py: 'zui3', en: 'mouth',
            variant: { s: '嘴巴', py: 'zui3 ba5', label: 'full colloquial form' } },
          { s: '牙', py: 'ya2', en: 'tooth; teeth',
            variant: { s: '牙齿', py: 'ya2 chi3', label: 'more precise' } },
          { s: '舌头', py: 'she2 tou5', en: 'tongue' },
        ],
      },
      {
        heading: 'Torso & limbs',
        words: [
          { s: '脖子', py: 'bo2 zi5', en: 'neck' },
          { s: '肩膀', py: 'jian1 bang3', en: 'shoulders' },
          { s: '手臂', py: 'shou3 bi4', en: 'arm' },
          { s: '手', py: 'shou3', en: 'hand' },
          { s: '手指', py: 'shou3 zhi3', en: 'finger' },
          { s: '胸', py: 'xiong1', en: 'chest' },
          { s: '背', py: 'bei4', en: 'back' },
          { s: '肚子', py: 'du4 zi5', en: 'stomach; belly' },
          { s: '腿', py: 'tui3', en: 'leg' },
          { s: '膝盖', py: 'xi1 gai4', en: 'knee' },
          { s: '脚', py: 'jiao3', en: 'foot' },
          { s: '脚趾', py: 'jiao3 zhi3', en: 'toe' },
        ],
      },
      {
        heading: 'Health',
        words: [
          { s: '疼', py: 'teng2', en: 'pain; to hurt',
            variant: { s: '痛', py: 'tong4', label: 'also common, varies by region' } },
          { s: '头疼', py: 'tou2 teng2', en: 'headache' },
          { s: '发烧', py: 'fa1 shao1', en: 'fever; to have a fever' },
          { s: '咳嗽', py: 'ke2 sou5', en: 'cough; to cough' },
          { s: '过敏', py: 'guo4 min3', en: 'allergy; to be allergic' },
          { s: '生病', py: 'sheng1 bing4', en: 'to get sick; to fall ill' },
          { s: '医生', py: 'yi1 sheng1', en: 'doctor' },
          { s: '医院', py: 'yi1 yuan4', en: 'hospital' },
          { s: '药', py: 'yao4', en: 'medicine; drug' },
        ],
      },
    ],
  },

  animals: {
    sections: [
      {
        heading: 'Pets & farm animals',
        words: [
          { s: '猫', py: 'mao1', en: 'cat' },
          { s: '狗', py: 'gou3', en: 'dog' },
          { s: '兔子', py: 'tu4 zi5', en: 'rabbit' },
          { s: '仓鼠', py: 'cang1 shu3', en: 'hamster' },
          { s: '猪', py: 'zhu1', en: 'pig' },
          { s: '牛', py: 'niu2', en: 'cow; ox' },
          { s: '羊', py: 'yang2', en: 'sheep; goat' },
          { s: '马', py: 'ma3', en: 'horse' },
          { s: '驴', py: 'lu:2', en: 'donkey' },
          { s: '鸡', py: 'ji1', en: 'chicken' },
          { s: '鸭子', py: 'ya1 zi5', en: 'duck' },
        ],
      },
      {
        heading: 'Wild mammals',
        words: [
          { s: '鹿', py: 'lu4', en: 'deer' },
          { s: '老虎', py: 'lao3 hu3', en: 'tiger' },
          { s: '狮子', py: 'shi1 zi3', en: 'lion' },
          { s: '熊猫', py: 'xiong2 mao1', en: 'panda' },
          { s: '熊', py: 'xiong2', en: 'bear' },
          { s: '猴子', py: 'hou2 zi5', en: 'monkey' },
          { s: '大猩猩', py: 'da4 xing1 xing5', en: 'gorilla' },
          { s: '大象', py: 'da4 xiang4', en: 'elephant' },
          { s: '长颈鹿', py: 'chang2 jing3 lu4', en: 'giraffe' },
          { s: '河马', py: 'he2 ma3', en: 'hippopotamus' },
          { s: '犀牛', py: 'xi1 niu2', en: 'rhinoceros' },
          { s: '狐狸', py: 'hu2 li5', en: 'fox' },
          { s: '狼', py: 'lang2', en: 'wolf' },
          { s: '蝙蝠', py: 'bian1 fu2', en: 'bat' },
          { s: '龙', py: 'long2', en: 'dragon' },
        ],
      },
      {
        heading: 'Birds & reptiles',
        words: [
          { s: '鸟', py: 'niao3', en: 'bird' },
          { s: '老鹰', py: 'lao3 ying1', en: 'eagle' },
          { s: '猫头鹰', py: 'mao1 tou2 ying1', en: 'owl' },
          { s: '乌龟', py: 'wu1 gui1', en: 'turtle; tortoise' },
          { s: '鳄鱼', py: 'e4 yu2', en: 'crocodile' },
          { s: '蛇', py: 'she2', en: 'snake' },
          { s: '青蛙', py: 'qing1 wa1', en: 'frog' },
        ],
      },
      {
        heading: 'Aquatic creatures',
        words: [
          { s: '鱼', py: 'yu2', en: 'fish' },
          { s: '金鱼', py: 'jin1 yu2', en: 'goldfish' },
          { s: '鲤鱼', py: 'li3 yu2', en: 'carp' },
          { s: '三文鱼', py: 'san1 wen2 yu2', en: 'salmon',
            variant: { s: '鲑鱼', py: 'gui1 yu2', label: 'Taiwan' } },
          { s: '鲸鱼', py: 'jing1 yu2', en: 'whale' },
          { s: '海豚', py: 'hai3 tun2', en: 'dolphin' },
          { s: '鲨鱼', py: 'sha1 yu2', en: 'shark' },
          { s: '章鱼', py: 'zhang1 yu2', en: 'octopus' },
          { s: '螃蟹', py: 'pang2 xie4', en: 'crab' },
        ],
      },
      {
        heading: 'Insects',
        words: [
          { s: '蝴蝶', py: 'hu2 die2', en: 'butterfly' },
          { s: '蚂蚁', py: 'ma3 yi3', en: 'ant' },
          { s: '蟑螂', py: 'zhang1 lang2', en: 'cockroach' },
          { s: '蚊子', py: 'wen2 zi5', en: 'mosquito' },
          { s: '蜜蜂', py: 'mi4 feng1', en: 'bee' },
          { s: '苍蝇', py: 'cang1 ying5', en: 'fly' },
        ],
      },
    ],
  },
};
